language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

branches:
  only:
    - master

install:
  - travis_retry composer self-update
  - composer install
  - composer require satooshi/php-coveralls

script: composer test

after_success:
  - php vendor/bin/coveralls -v; fi;