language: php
dist: focal
os:
  - linux

branches:
  only:
    - master

install:
  - travis_retry composer self-update
  - composer install

stages:
  - Testing

jobs:
  include:
    - stage: Testing
      name: Running unit tests on PHP 7.2
      php: 7.2
      script: composer test

    - stage: Testing
      name: Running unit tests on PHP 7.3
      php: 7.3
      script: composer test

    - stage: Testing
      name: Running unit tests on PHP 7.4
      php: 7.4
      script: 
        - composer test

    - stage: Testing
      name: Running unit tests on PHP 8.0
      php: 8.0.0
      script: 
        - composer test
        - vendor/bin/php-coveralls -v
