language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

branches:
  only:
    - master

install:
  - travis_retry composer self-update
  - composer install

script: composer testdox

after_success:
  - sh -c 'if( [ "$TRAVIS_PHP_VERSION" != "7.4" ] ); then vendor/bin/php-coveralls -v