language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

branches:
  only:
    - master

install:
  - travis_retry composer self-update
  - composer install

stages:
  - test
  - coverage

jobs:
  include:
    - stage: test
      name: Running unit tests
      script: composer testdox

    - stage: coverage
      name: "Sending code coverage"
      php: 7.4
      script: vendor/bin/php-coveralls -v